name: goreleaser

# Build on tags on master
on:
  create:
    branches:
      - master

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.13.1

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_RELEASE_TOKEN }}
        with:
          version: latest
          args: release
